apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-eh5z
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0011-tenant/tkrw-pr712-0075-0011-app/devfile-sample-eh5z@sha256:85a9bb6857d36a5ffe1fcf1f6cbb26c3a78447d009ec9592a7ae813742b69c37
        name: my-nodejs
        resources: {}
status: {}
